---
title: 'Exercice 2.2 : Indexation et fichier de données'
author: "Visseho Adjiwanou, PhD."
date: "8/06/2021"
output:
  beamer_presentation: default
  ioslides_presentation: default
---


Vous utiliserez le fichier de données **migration** fourni sous format **.csv.**

## Exercice 1

1. Importer le fichier migration.csv dans RStudio.
2. Changer les noms des variables **Value**, **INT** et **GEO** respectivement en **persons**, **type** et **location**
3. Créer un fichier de données **mig** filtrant les valeurs de l'Ontario et du Québec dont la migration trimestrielle (variable **persons**) est supérieure à la migration trimestrielle moyenne.

## Exercice 2

1. Dans le fichier **mig**, changer les valeurs de la variable **persons** de façon à ce que les valeurs soient négatives si le type de migration est **Out-migrants**.
2. A partir du fichier **mig**, créer une variable fictive (binaire) **out_mig** qui prend la valeur 1 si la migration trimestrielle est négative, puis compter le nombre d'observations correspondantes dans chaque province/territoire.

## Exercice 3

1. Dans le fichier **mig**, scinder la variable **Ref_Date** en deux variable **year** et **month**
2. Calculer le minimum, le maximum et l'écart-type de la migration trimestrielle pour chaque année.
